# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Update
      - name: Update package database
        run: sudo apt-get update -qy

      # Install deps
      - name: Install dependencies
        run: sudo apt-get install -y libfuse2 libgtk-3-dev

      # Build flips
      - name: Building flips...
        run: sh scripts/build_flips.sh

      # Make appimage
      - name: Making appimage...
        run: sh scripts/make_appimage.sh

      - name: Create release...
        uses: actions/create-release@v1
        id: create_release
        with:
            draft: false
            prerelease: false
            release_name: "commit: fdd5c6e"
            tag_name: ${{ github.ref }}
            body_path: "last_commit: https://github.com/Alcaro/Flips/commit/fdd5c6e34285beef5b9be759c9b91390df486c66"
        env:
            GITHUB_TOKEN: ${{ github.token }}

      # Release appimage
      - name: Release appimage..
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: Flips/Flips-x86_64.AppImage
            asset_name: Flips-x86_64.AppImage
            asset_content_type: application/x-iso9660-appimage

      # Release appimage zsync
      - name: Release appimage zsync..
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: Flips/Flips-x86_64.AppImage.zsync
            asset_name: Flips-x86_64.AppImage.zsync
            asset_content_type: application/x-iso9660-appimage
